### ISSUE TITLE
Funcionalidad

### ISSUE THREAD

**Issue by luisalbertoc** [rtorres90/maildropcc-reader#1]
¿Para qué sirve?

**Comment by rtorres90** [comment]
Maildrop.cc es un aplicación web para crear cuentas de emails abiertas a todo el mundo con la finalidad de utilizarla para pruebas. Por ejemplo: tu puedes crear un correo llamado test123 para recibir correos. Ayuda mucho en el unit testing de procesos de creación de usuarios, procesos de recuperación de contraseñas, correos de bienvenida, etc.

Ahora respondiendo a la pregunta, maildropcc-reader es un librería python que permite leer correos de una cuenta maildrop.cc. La motivación para crear esta librería fue tener una solución solida para la automatización de lectura de correos, ya que, maildrop.cc no tiene ningún tipo de filtro aplicado, entonces puedes recibir cualquier tipo de correo de prueba sin ser declarado como spam (cosa que pasa al usar gmail, outlook y yahoo).

Ejemplo:
```
from maildropcc_reader import MailDrop

md = MailDrop('asdf')
print md.get_emails()
```

**Comment by rtorres90** [comment]
Se añadió documentación con código de ejemplo.
